# for whatever reason, typed-settings converts underscores to dashes
[pico-to-mqtt]

[pico-to-mqtt.mqtt-config]
path_to_mqtt_client_cert = "/etc/pico-to-mqtt/mqtt/ssl/certs/pico-to-mqtt-mqtt-client.crt"
path_to_mqtt_client_key = "/etc/pico-to-mqtt/mqtt/ssl/certs/pico-to-mqtt-mqtt-client.key"
path_to_mqtt_client_ca = "/etc/pico-to-mqtt/mqtt/ssl/root-cert/pihome-ca.pem"
hostname = "pihome.run"
port = 8883

[pico-to-mqtt.caseta-config]
caseta_bridge_hostname = "caseta.run"
path_to_caseta_client_cert = "/etc/pico-to-mqtt/pylutron-caseta/ssl/certs/caseta.run.crt"
path_to_caseta_client_key = "/etc/pico-to-mqtt/pylutron-caseta/ssl/certs/caseta.run.key"
path_to_caseta_client_ca = "/etc/pico-to-mqtt/pylutron-caseta/ssl/certs/caseta.run-bridge.crt"
