default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - "172.22.0.10" # the IP specified in ../../traefik/docker-compose.yml

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
