default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - "172.22.0.10" # the IP specified in ../../traefik/docker-compose.yml

scene:
  !include scenes.yaml
automation:
  !include automations.yaml
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

logger:
  default: info
script:
  !include scripts.yaml
notify:
  - name: configuration_notifier
    platform: file
    filename: /config/dumped_configuration.txt
