mqtt:
  base_topic: zigbee2mqtt
  server: mqtts://mqtt:8883 # this needs to be configured with the actual hostname
  keepalive: 60
  reject_unauthorized: true
  user: "!secret.yaml user"
  password: "!secret.yaml password"
  ca: "/app/conf/ssl/root-cert/pihome-ca.pem"
  key: "/app/conf/ssl/cert/zigbee2mqtt-mqtt-client.key"
  cert: "/app/conf/ssl/cert/zigbee2mqtt-mqtt-client.crt"
  version: 4
serial:
  port: "/dev/serial/by-id/zigbee-serial-adapter"
frontend:
  port: 8080
permit_join: false
advanced:
  network_key: "!secret.yaml network_key"
homeassistant: true
