version: '3'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./volumes/homebridge:/homebridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homebridge.rule=Host(`homebridge.pihome.run`)"
      - "traefik.http.routers.homebridge.entrypoints=websecure"
      - "traefik.http.routers.homebridge.tls=true"
      - "traefik.http.services.homebridge.loadbalancer.server.port=8581"
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
