version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      - 'TZ=America/New_York'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=(Host(`pihole.pihome.run`) && PathPrefix(`/admin`))"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.middlewares.pihole-add-admin-path.redirectregex.regex=^https://pihole.pihome.run/?$"
      - "traefik.http.middlewares.pihole-add-admin-path.redirectregex.replacement=https://pihole.pihome.run/admin"
      - "traefik.http.routers.pihole.middlewares=pihole-add-admin-path"
    volumes:
       - './etc-pihole/:/etc/pihole'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d'
    networks:
      traefik-net:
        ipv4_address: 172.22.0.11
    restart: unless-stopped
networks:
  traefik-net:
    external: true
