version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      - 'TZ=America/New_York'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.pihome.run`)"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-net"
    volumes:
       - './etc-pihole/:/etc/pihole'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d'
    networks:
      - traefik-net
    restart: unless-stopped
networks:
  traefik-net:
    external: true
