version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
      - "./mosquitto-ssl:/mosquitto/conf/ssl"
      - "./mosquitto-passwd:/mosquitto/conf/passwd"
    ports:
      - "8883:8883"
      - "9001:9001"
    networks:
      traefik-net:
        ipv4_address: 172.22.0.12
    command: "mosquitto -c /mosquitto/conf/mosquitto.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - ./zigbee2mqtt-ssl:/app/conf/ssl
      - /run/udev:/run/udev:ro
    networks:
      traefik-net:
        ipv4_address: 172.22.0.13
    environment:
      - 'TZ=America/New_York'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.z2m.rule=Host(`zigbee2mqtt.pihome.run`, `z2m.pihome.run`)"
      - "traefik.http.routers.z2m.entrypoints=websecure"
      - "traefik.http.routers.z2m.tls=true"
      - "traefik.http.services.z2m.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.middlewares.redirect-z2m.redirectregex.regex=^https://z2m.pihome.run/(.*)"
      - "traefik.http.middlewares.redirect-z2m.redirectregex.replacement=https://zigbee2mqtt.pihome.run/$${1}"
      - "traefik.http.middlewares.redirect-z2m.redirectregex.permanent=true"
      - "traefik.http.routers.z2m.middlewares=redirect-z2m"
    devices:
      # specify the adapter path from zigbee2mqtt-data/configuration.yaml serial.port
      - /dev/serial/by-id/PLACEHOLDER:/dev/serial/by-id/PLACEHOLDER

networks:
  traefik-net:
    external: true
