version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto/data"
      - "./mosquitto-config:/mosquitto/conf:ro"
      - "./mosquitto-ssl/cert-${CERT_VERSION:?err}:/mosquitto-ssl/cert:ro"
      - "./mosquitto-ssl/root-cert-${ROOT_CERT_VERSION:?err}:/mosquitto-ssl/root-cert:ro"
    ports:
      - "8883:8883"
      - "9001:9001"
    networks:
      traefik-net:
        ipv4_address: 172.22.0.12
    command: "mosquitto -c /mosquitto/conf/mosquitto.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - './zigbee2mqtt-data:/app/data'
      - './zigbee2mqtt-ssl/cert-${CERT_VERSION:?err}:/app/conf/ssl/cert:ro'
      - './zigbee2mqtt-ssl/root-cert-${ROOT_CERT_VERSION:?err}:/app/conf/ssl/root-cert:ro'
      - '/run/udev:/run/udev:ro'
    networks:
      traefik-net:
        ipv4_address: 172.22.0.13
    environment:
      - 'TZ=America/New_York'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.z2m.rule=Host(`zigbee2mqtt.${PIHOME_HOSTNAME:?err}.${PIHOME_TLD:?err}`, `z2m.${PIHOME_HOSTNAME:?err}.${PIHOME_TLD:?err}`)"
      - "traefik.http.routers.z2m.entrypoints=websecure"
      - "traefik.http.routers.z2m.tls=true"
      - "traefik.http.services.z2m.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.middlewares.redirect-z2m.redirectregex.regex=^https://z2m.${PIHOME_HOSTNAME:?err}.${PIHOME_TLD:?err}/(.*)"
      - "traefik.http.middlewares.redirect-z2m.redirectregex.replacement=https://zigbee2mqtt.${PIHOME_HOSTNAME:?err}.${PIHOME_TLD:?err}/$${1}"
      - "traefik.http.middlewares.redirect-z2m.redirectregex.permanent=true"
      - "traefik.http.routers.z2m.middlewares=redirect-z2m"
    devices:
      # specify the adapter path from zigbee2mqtt-data/configuration.yaml serial.port
      - ${ZIGBEE_SERIAL_ADAPTER:?err}:/dev/serial/by-id/zigbee-serial-adapter

networks:
  traefik-net:
    external: true
