version: '3'
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.${PIHOME_HOSTNAME:?err}.${PIHOME_TLD:?err}`, `hass.${PIHOME_HOSTNAME:?err}.${PIHOME_TLD:?err}`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls=true"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.http.middlewares.redirect-hass.redirectregex.regex=^https://hass.${PIHOME_HOSTNAME:?err}.${PIHOME_TLD:?err}/(.*)"
      - "traefik.http.middlewares.redirect-hass.redirectregex.replacement=https://homeassistant.${PIHOME_HOSTNAME:?err}.${PIHOME_TLD:?err}/$${1}"
      - "traefik.http.middlewares.redirect-hass.redirectregex.permanent=true"
      - "traefik.http.routers.homeassistant.middlewares=redirect-hass"
