version: '3'
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.pihome.run`)"
      - "traefik.http.routers.homebridge.entrypoints=websecure"
      - "traefik.http.routers.homebridge.tls=true"
      - "traefik.http.services.homebridge.loadbalancer.server.port=8123"
