version: '3'

services:
  pico_to_mqtt:
    image: pico_to_mqtt:latest
    volumes:
      - "./pico-to-mqtt-config:/etc/pico-to-mqtt/config"
      - "./pico-to-mqtt-ssl/mqtt/cert-${CERT_VERSION:?err}:/etc/pico-to-mqtt/mqtt/ssl/certs"
      - "./pico-to-mqtt-ssl/mqtt/root-cert-${ROOT_CERT_VERSION:?err}/etc/pico-to-mqtt/mqtt/ssl/root-cert"
      - "./pico-to-mqtt-ssl/pylutron-caseta/cert-${CASETA_CERT_VERSION:?err}/etc/pico-to-mqtt/pylutron-caseta/ssl/certs"
    restart: unless-stopped
    environment:
      - "PICO_TO_MQTT_SETTINGS": "/etc/pico-to-mqtt/config/default-settings.toml:/etc/pico-to-mqtt/config/settings.toml:/etc/pico_to_mqtt/secrets.toml"
      - "LOGLEVEL": "${PICO_TO_MQTT_LOGLEVEL:-INFO}"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
